{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- range .Values.rangeServiceMonitor }}
apiVersion: apisix.apache.org/v2
kind: ServiceMonitor
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  labels:
    release: {{ .labels.release | quote }}
spec:
  endpoints:
    - interval: 15s
      path: {{ .endpoints.path | quote }}
      port: {{ .endpoints.port | quote }}
  selector:
    matchLabels:
      {{ toYaml .selector.matchLabels | indent 6 }}
---
{{- end }}
{{- end }}