apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: {{ .Values.name | quote }}
spec:
  ingressClassName: {{ .Values.ingressClassName | quote }}
  plugins:
    - name: {{ .Values.plugins.name | quote }}
      enable: {{ .Values.plugins.enable }}
      config:
{{ toYaml .Values.plugins.config | indent 8 }}
