{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: apisix.apache.org/v2
kind: ServiceMonitor
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    release: {{ .Values.labels.release | quote }}
spec:
  endpoints:
    - interval: 15s
      path: {{ .Values.endpoints.path | quote }}
      port: {{ .Values.endpoints.port | quote }}
  selector:
    matchLabels:
      {{ toYaml .Values.selector.matchLabels | indent 6 }}
{{- end }}
