apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: {{ .Values.name | quote }}
spec:
  ingressClassName: {{ .Values.ingress_class_name | quote }}
  plugins:
    - name: {{ .Values.plugin.name | quote }}
      enable: {{ .Values.plugin.enable }}
      config:
{{ toYaml .Values.config | indent 8 }}
